name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  update-k8s-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit changes to k8s repo (if any)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-deploy: update manifests"
          git push
